# Generated by Django 4.2.1 on 2023-05-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('user_name', models.TextField(blank=True, null=True, verbose_name='Username')),
                ('first_name', models.TextField(verbose_name='Имя')),
                ('last_name', models.TextField(blank=True, null=True, verbose_name='Фамилия')),
                ('ballance', models.FloatField(blank=True, null=True, verbose_name='Балланс')),
                ('ban', models.IntegerField(choices=[(1, 'Заблокирован'), (0, 'Нет блокировки')], verbose_name='Бан')),
                ('user_date', models.DateTimeField(verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'storage_users',
            },
        ),
    ]
