# Generated by Django 4.2.1 on 2023-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_standart', models.BigIntegerField(verbose_name='Запрос по фио стандартный')),
            ],
            options={
                'verbose_name': 'Тарифы',
                'verbose_name_plural': 'Тарифы',
                'db_table': 'price',
            },
        ),
    ]
