# Generated by Django 4.2.1 on 2023-05-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0002_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='name_full',
            field=models.TextField(blank=True, null=True, verbose_name='Запрос по фио расширенный'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='name_standart',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Запрос по фио стандартный'),
        ),
    ]
