# Generated by Django 4.2.1 on 2023-06-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0003_prices_name_full_alter_prices_name_standart'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='phone',
            field=models.FloatField(blank=True, null=True, verbose_name='Запрос по номеру телефона'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='name_full',
            field=models.FloatField(blank=True, null=True, verbose_name='Запрос по фио расширенный'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='name_standart',
            field=models.FloatField(blank=True, null=True, verbose_name='Запрос по фио стандартный'),
        ),
    ]
