# Generated by Django 4.2.1 on 2023-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0004_prices_phone_alter_prices_name_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='passport',
            field=models.FloatField(blank=True, null=True, verbose_name='Запрос по паспорту'),
        ),
    ]
