# Generated by Django 4.2.1 on 2023-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0005_prices_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='avto',
            field=models.FloatField(blank=True, null=True, verbose_name='Запрос по номеру авто'),
        ),
        migrations.AddField(
            model_name='prices',
            name='email',
            field=models.FloatField(blank=True, null=True, verbose_name='Запрос по email'),
        ),
        migrations.AddField(
            model_name='prices',
            name='inn',
            field=models.FloatField(blank=True, null=True, verbose_name='Запрос по ИНН'),
        ),
        migrations.AddField(
            model_name='prices',
            name='inn_fl',
            field=models.FloatField(blank=True, null=True, verbose_name='Запрос по ИНН физ.лиза'),
        ),
        migrations.AddField(
            model_name='prices',
            name='snils',
            field=models.FloatField(blank=True, null=True, verbose_name='Запрос по СНИЛС'),
        ),
        migrations.AddField(
            model_name='prices',
            name='vin',
            field=models.FloatField(blank=True, null=True, verbose_name='Запрос по VIN'),
        ),
    ]
