# Generated by Django 4.2.1 on 2023-06-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0006_prices_avto_prices_email_prices_inn_prices_inn_fl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='scoring',
            field=models.FloatField(blank=True, null=True, verbose_name='Скоринг'),
        ),
    ]
