# Generated by Django 4.2.1 on 2023-06-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0007_prices_scoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('type_request', models.TextField(blank=True, null=True, verbose_name='Тип запроса')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Данные для запроса')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Запросы',
                'verbose_name_plural': 'Запросы',
                'db_table': 'request_storage',
            },
        ),
    ]
