# Generated by Django 4.2.1 on 2023-06-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0008_request_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(verbose_name='order_id')),
                ('pay_id', models.BigIntegerField(verbose_name='pay_id')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('sign', models.TextField(verbose_name='Хеш')),
            ],
        ),
    ]
