# Generated by Django 4.2.1 on 2023-06-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0009_pay_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_data',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pay_data',
            name='order_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pay_data',
            name='pay_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pay_data',
            name='sign',
            field=models.TextField(),
        ),
    ]
