# Generated by Django 4.2.1 on 2023-06-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0010_alter_pay_data_amount_alter_pay_data_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_data',
            name='us_key',
            field=models.TextField(default=1),
        ),
    ]
