# Generated by Django 4.2.1 on 2023-06-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0011_pay_data_us_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay_data',
            options={'verbose_name': 'Запросы', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterField(
            model_name='pay_data',
            name='us_key',
            field=models.TextField(blank=True, default=1, null=True),
        ),
        migrations.AlterModelTable(
            name='pay_data',
            table='users_manage_pay_data',
        ),
    ]
