# Generated by Django 4.2.2 on 2023-06-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0012_alter_pay_data_options_alter_pay_data_us_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Сумма')),
                ('hashmd5', models.TextField(blank=True, null=True, verbose_name='Хеш проверки')),
                ('status', models.TextField(verbose_name='Статус')),
                ('create_date', models.DateTimeField(verbose_name='Дата cоздания')),
            ],
            options={
                'verbose_name': 'Пополнения фиат',
                'verbose_name_plural': 'Пополнения фиат',
                'db_table': 'recipient',
            },
        ),
        migrations.AlterField(
            model_name='pay_data',
            name='us_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
